config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about', to: 'home#about'

  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/map', to: 'map#show'

  get '/tmdb', to: 'tmdb#index'
  
  get '/user_images/:filename', to: 'users#user_image', as: 'user_image'

  resources :users do
    resources :movies do
      resources :comments, only: [:create,:edit,:update,:destroy]
    end
  end

  resources :notifications do
    member do
      patch :mark_as_read
    end
  end

end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = email.downcase}
  has_one_attached :picture
  has_many :movies, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def notifications
    # 通知モデルとの関連付けにより、通知を取得するメソッドを定義します
    Notification.where(user_id: self.id)
  end
  
  def unread_notifications
    notifications.where(read: false)
  end

  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: {maximum: 100},
  format: {with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true
 
  validates :picture, content_type: { in: %w[image/jpeg image/gif image/png],
    message: "有効なフォーマットではありません" },
    size: { less_than: 5.megabytes, message: " 5MBを超える画像はアップロードできません" }

    def favorite?(movie)
      movies.exists?(movie.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only:[:edit]
  before_action :logged_in_user, only:[:edit,:update,:destroy]

  def like
    @movie.update(likes: true)
    redirect_to user_movie_path(current_user, @movie)
  end

  def unlike
    @movie.update(likes: false)
    redirect_to user_movie_path(current_user, @movie)
  end


  def login_page
  end

  def login
    @user=User.find_by(email: params[:email], password: params[:password])
    if @user
      flash[:notice]="ようこそ#{@user.name}さん"
      redirect_to user_url
    else
      render :login_page
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @notification = Notification.where(read: false)
    @movie = @user.movies.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      # ここ変更したところ5/19
      if params[:user][:picture].present?
       @user.picture.attach(params[:user][:picture])
      else
       default_picture_path = Rails.root.join('public', 'user_images', 'no_image.png')
       default_picture = File.open(default_picture_path)
       @user.picture.attach(io: default_picture, filename: 'no_image.png')
      end
         flash[:success] = "ユーザー登録しました"
         redirect_to @user
    else
      flash.now[:danger]="ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
    
  end

  def update
    @user = User.find(params[:id])
    @user.picture.attach(params[:user][:picture]) 
    if @user.update(user_update_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render :show
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success]="#{@user.name}を削除しました"
    redirect_to users_url
  end

 

  def user_image
    filename = params[:filename]
    send_file Rails.root.join('public', 'user_images', filename), type: 'image/png', disposition: 'inline'
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:picture)
  end

  def user_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
  end
end

app/views/users/_form.html.erb
 
 
 <%= form_with model: @user, url: users_path, multipart: true do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :picture, '画像(5Gまで)',class: "label-#{yield(:class_text)}"  %>
  <%= f.file_field :picture,  onchange: "pictureImage(this);", accept: "image/jpeg,image/gif,image/png"%>
  <div id="picture" >
    <img id="picture_preview" class="mb-3" width="100">
  </div>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Confirmation", class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  
  <% if @user.picture.present? %> <!-- @user.pictureが存在する場合のみ image_tag を使用(if文ないとエラーが出る) -->
    <span style="display: block; text-align: center; padding-top:10px;color:gray"><b>[現在登録されている画像]</b></span><br>
    <%= image_tag @user.picture, width: 200, class: "mb-2", style: "display: block; margin-left: auto; margin-right: auto;" %>
  <% end %>
<% end %>


<script>
  function pictureImage(obj){
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('picture_preview').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
  }
</script>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<%= stylesheet_link_tag 'movies' %>
<div class="user_edit">
<div class="container">
<h1>ユーザー情報の編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_with model: @user, url: user_path, multipart: true do |f| %>
    <%= render 'shared/error_messages', object: @user %>

      <%= f.label :picture, '画像(5Gまで)',class: "label-#{yield(:class_text)}"  %>
      <%= f.file_field :picture,  onchange: "pictureImage(this);", accept: "image/jpeg,image/gif,image/png"%>
      <div id="picture" >
        <img id="picture_preview" class="mb-3" width="100">
      </div>

      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation", class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
      
      <% if @user.picture.present? %> <!-- @user.pictureが存在する場合のみ image_tag を使用(if文ないとエラーが出る) -->
        <span style="display: block; text-align: center; padding-top:10px;color:gray"><b>[現在登録されている画像]</b></span><br>
        <%= image_tag @user.picture, width: 200, class: "mb-2", style: "display: block; margin-left: auto; margin-right: auto;" %>
      <% end %>
    <% end %>


<script>
  function pictureImage(obj){
      var fileReader = new FileReader();
      fileReader.onload = (function() {
        document.getElementById('picture_preview').src = fileReader.result;
      });
      fileReader.readAsDataURL(obj.files[0]);
  }
</script>

  </div>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1 class="index_h1">ALL USER</h1>
<div class ="index-main">
 <div class="container">
    <% @users.each do |user|%>
      <div class="users-index">
        <div class="user-right">
         <% if user.picture.attached? %><br>
          <%= image_tag user.picture, width: 50, class: "mb-2 rounded-circle" %>
          <% else %>
          <%= image_tag "/user_images/no_image.png", width: 50, class: "mb-2 rounded-circle" %>
          <% end %>
          <%= link_to user.name, user_path(user.id)%>
          <% if current_user.admin?%>
           <%= link_to "削除", user, data: {turbo_method: :delete, confirem:"#{user.name}を削除してよろしいですか？"},class: "btn btn-danger"%>
          <% else%>
          <% end %> 
        </div>
      </div>
    <% end %>
 </div>
</div>mm

app/views/users/new.html.erb
<% provide(:title,"新規会員登録")%>
<% provide(:class_text, "新規")%>
<% provide(:button_text, "新規登録")%>

<div class="main users-new">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="form-heading">新規ユーザー登録</div>
          <%= render "form"%>
          
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'movies' %>
<div class="main user-show">
  <div class="container">
    <h1 class="user-headding"></h1>
      <div class="users-show-item">
        <div class="user-right">
        <% if @user.picture.attached? %><br>
          <%= image_tag @user.picture, width: 200, class: "mb-2" %><br>
        <% else %>
          <%= image_tag "/user_images/no_image.png", width: 50, class: "mb-2 rounded-circle" %><br>
        <% end %>
          <%= @user.name %><br>
          <%= @user.email%><br>
          <div class="horizontal-line"></div>
         <% if current_user && current_user==@user%>
          <%= link_to"+",new_user_movie_url(@user),class: "btn btn-success btn-text"%><br>
         <% end %>
        </div>
        <div class="movie_show_index">
          <div class="container text-center">
            <div class="row">
              <div class="col-md-12 col-mi-offset-12">
               <% if @user.movies.any? %>
               <h1>Collection</h1>
               <% if @notification.exists?%>
               <li>コメント通知</li><br>
                <% @notification.unread.each do |notification|%>
                  <%= notification.user.name%>さんより<br>
                  【<%= notification.comment.movie.title%>】の投稿へコメントがありました！<br> 
                  <%= notification.comment.content%>
                  <%= button_to "☑️",mark_as_read_notification_path(notification), method: :patch%>
                <% end %>
               <% end %>

                <% @user.movies.each do |movie| %>
                  <div class="col-md-4 show_index">
                      <table class ="table">
                        <thead>
                        <tr>
                          <th></th><br>	 
                          <th></th>	       
                          <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr >
                        <td >
                        <pre><%= movie.title %></pre>
                        </td>
                        <td>
                        <pre><%= movie.director %></pre>
                        </td>
                        </tr>
                        </tbody>
                      </table>
                        <% if movie.img? %>
                        <div class="d-flex justify-content-center">
                          <p><%= image_tag movie.img.url, style: "max-height: 200px; width: auto" %></p>
                        </div>
                        <% else %>
                        <div class="d-flex justify-content-center">
                          <p><%= image_tag "movie_no_image.png", style: "max-height: 200px; width: auto" %></p>
                        </div>
                        <% end %>
                        <% if current_user && current_user==@user%>
                        <%= link_to "編集", edit_user_movie_path(@user, id: movie.id), class: "btn btn-success" %>
                        <%= link_to "👀",user_movie_path(@user,movie.id), class:"btn btn-primary"%>
                        <%= link_to "削除",user_movie_path(@user, movie.id),method: :delete ,data: {confirm: "削除してよろしいでしょうか？"},
                        class: "btn btn-secondary"%>
                        <% else %>
                        <%= link_to "👀",user_movie_path(@user,movie.id), class:"btn btn-primary"%>
                        <% end %>
                  </div>
                <% end %>


                <%else%>
                  <p>映画のレビューを書いてみよう！</p>
                  <div class="movie-container">
                  <div class="movie_item">
                  <%= image_tag("movie_no_image.png",class:"user_show_movie_expample",width:"200px",height:"auto")%>
                  <p>タイトルA</p>
                <% end %>
               </div>
            </div>
          </div>
      </div>
  </div>
</div>