config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'about', to: 'home#about'

  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/map', to: 'map#show'

  get '/tmdb', to: 'tmdb#index'
  
  get '/user_images/:filename', to: 'users#user_image', as: 'user_image'

  resources :users do
    resources :movies do
      resources :comments, only: [:create,:edit,:update,:destroy]
    end
  end

  resources :notifications do
    member do
      patch :mark_as_read
    end
  end

end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# bootstrapの機能を実装するためのコード %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'rails-ujs' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <header class="navbar navbar-fixed-top navbar-inverse">
        <%= link_to "MOVIE TALK", root_path, id:"logo"%>
          <nav>
            <ul class="nav nav-pills ">
              <% if logged_in? %>
                <li class="nav-item"><%= link_to"現在上映中の映画",tmdb_path%></li>
                <li class="nav-item"><%= link_to "MOVIE TALKについて", about_path %></li>
                <li class="nav-item"><%= link_to "Showページ", user_path(current_user) %></li>
                <li class="nav-item"><%= link_to "入場者一覧", users_path %></li>
                <li class="nav-item"><%= link_to "ユーザー情報編集", edit_user_path(current_user) %></li>
                <li class="nav-item"><%= link_to "Log out", logout_path,method: :delete, data: { turbo_method: :delete } %></li>
              <% else %>
                <li class="nav-item"><%= link_to"現在上映中の映画",tmdb_path%></li>
                <li class="nav-item"><%= link_to "MOVIE TALKについて", about_path %></li>
                <li class="nav-item"><%= link_to "入館", login_path %></li>
                <li class="nav-item"><%= link_to "新規登録", new_user_path %></li>
              <% end %>
            </ul>
          </nav>
    </header>

  <body>
    <div id="main-message">
      <div class="container">
        <% flash.each do |message_type,msg|%>
          <div class="alert alert-<%=message_type%>"><%= msg%></div>
        <% end %>
      </div>
    </div>
    <div class = "container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>

     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </body>
  
</html>